/// [LocalizationService] acts as the central translation repository for the application.
/// It provides localized string dictionaries for supported languages (English, Hindi, Tamil, and Telugu)
/// and exposes a safe [translate] method to dynamically fetch localized strings with fallback handling.
class LocalizationService {
  // Master map of supported languages and their corresponding key-value string translations
  static final Map<String, Map<String, String>> _translations = {
    'English': {
      'hello': 'Hello',
      'mind_today': "what's on your mind today?",
      'on_device_only': 'on this device only',
      'offline': 'offline',
      'start_something': 'START SOMETHING',
      'ask_anything': 'Ask anything',
      'ask_anything_sub': 'health · legal · personal · work',
      'voice_mode': 'Voice mode',
      'voice_mode_sub': 'Speak in your language',
      'ask_image': 'Ask an image',
      'ask_image_sub': 'Forms, labels, scripts',
      'panchang': 'Panchang',
      'panchang_sub': "today's tithi & muhurat",
      'ephemeral': 'Ephemeral',
      'ephemeral_sub': 'speak with no trace',
      'recent': 'RECENT',
      'home': 'Home',
      'chat': 'Chat',
      'library': 'Library',
      'you': 'You',
      'settings_pref': 'settings · preferences · about',
      'preferences': 'PREFERENCES',
      'language': 'Language',
      'security': 'Security',
      'security_sub': 'App lock · 2FA',
      'privacy_tiers': 'Privacy tiers',
      'privacy_tiers_sub': '2 active · how BrahmAI listens',
      'storage_purge': 'Storage & purge',
      'storage_purge_sub': '184 KB on device',
      'ephemeral_mode': 'Ephemeral mode',
      'about': 'ABOUT',
      'reset_prototype': 'Reset prototype',
      'built_in_india': 'Built in India. For the World.',
      'library_sub': 'every model · every memory · on this device',
      'on_this_device': 'ON THIS DEVICE',
      'active': 'active',
      'add': '+ add',
      'storage_used': 'STORAGE USED',
      'health_question': 'health question',
      'family': 'family',
      'work': 'work',
      'just_thinking': 'just thinking',
    },
    'हिन्दी': {
      'hello': 'नमस्ते',
      'mind_today': 'आज आपके मन में क्या है?',
      'on_device_only': 'केवल इसी डिवाइस पर',
      'offline': 'ऑफलाइन',
      'start_something': 'कुछ शुरू करें',
      'ask_anything': 'कुछ भी पूछें',
      'ask_anything_sub': 'स्वास्थ्य · कानूनी · व्यक्तिगत · कार्य',
      'voice_mode': 'वॉइस मोड',
      'voice_mode_sub': 'अपनी भाषा में बोलें',
      'ask_image': 'इमेज से पूछें',
      'ask_image_sub': 'फॉर्म, लेबल, स्क्रिप्ट',
      'panchang': 'पंचांग',
      'panchang_sub': 'आज की तिथि और मुहूर्त',
      'ephemeral': 'अल्पकालिक',
      'ephemeral_sub': 'बिना किसी निशान के बोलें',
      'recent': 'हाल ही में',
      'home': 'होम',
      'chat': 'चैट',
      'library': 'लाइब्रेरी',
      'you': 'आप',
      'settings_pref': 'सेटिंग्स · प्राथमिकताएं · बारे में',
      'preferences': 'प्राथमिकताएं',
      'language': 'भाषा',
      'security': 'सुरक्षा',
      'security_sub': 'ऐप लॉक · 2FA',
      'privacy_tiers': 'गोपनीयता स्तर',
      'privacy_tiers_sub': '2 सक्रिय · BrahmAI कैसे सुनता है',
      'storage_purge': 'स्टोरेज और पर्ज',
      'storage_purge_sub': 'डिवाइस पर 184 KB',
      'ephemeral_mode': 'अल्पकालिक मोड',
      'about': 'बारे में',
      'reset_prototype': 'प्रोटोटाइप रीसेट करें',
      'built_in_india': 'भारत में निर्मित। दुनिया के लिए।',
      'library_sub': 'हर मॉडल · हर मेमोरी · इस डिवाइस पर',
      'on_this_device': 'इस डिवाइस पर',
      'active': 'सक्रिय',
      'add': '+ जोड़ें',
      'storage_used': 'प्रयुक्त स्टोरेज',
      'health_question': 'स्वास्थ्य प्रश्न',
      'family': 'परिवार',
      'work': 'कार्य',
      'just_thinking': 'बस सोच रहा हूँ',
    },
    'தமிழ்': {
      'hello': 'வணக்கம்',
      'mind_today': 'இன்று என்ன மனதில் இருக்கிறது?',
      'on_device_only': 'இந்த சாதனத்தில் மட்டுமே',
      'offline': 'ஆகப்லைன்',
      'start_something': 'தொடங்குங்கள்',
      'ask_anything': 'எதையும் கேளுங்கள்',
      'ask_anything_sub': 'உடல்நலம் · சட்டம் · தனிப்பட்டது · வேலை',
      'voice_mode': 'குரல் வழியாக',
      'voice_mode_sub': 'உங்கள் மொழியில் பேசுங்கள்',
      'ask_image': 'படத்திலிருந்து கேளுங்கள்',
      'ask_image_sub': 'படிவம், லேபிள், எழுத்து',
      'panchang': 'பஞ்சாங்கம்',
      'panchang_sub': 'இன்றைய திதியும் முகூர்த்தமும்',
      'ephemeral': 'தற்காலிகம்',
      'ephemeral_sub': 'எந்தத் தடயமும் இல்லாமல்',
      'recent': 'சமீபத்தியவை',
      'home': 'முகப்பு',
      'chat': 'அரட்டை',
      'library': 'நூலகம்',
      'you': 'நீங்கள்',
      'settings_pref': 'அமைப்புகள் · விருப்பத்தேர்வுகள் · பற்றி',
      'preferences': 'விருப்பத்தேர்வுகள்',
      'language': 'மொழி',
      'security': 'பாதுகாப்பு',
      'security_sub': 'ஆப் லாக் · 2FA',
      'privacy_tiers': 'தனியுரிமை அடுக்குகள்',
      'privacy_tiers_sub': '2 செயலில் உள்ளன · BrahmAI எப்படி கேட்கிறது',
      'storage_purge': 'சேமிப்பு மற்றும் நீக்கம்',
      'storage_purge_sub': 'சாதனத்தில் 184 KB',
      'ephemeral_mode': 'தற்காலிக முறை',
      'about': 'பற்றி',
      'reset_prototype': 'மாதிரியை மீட்டமைக்கவும்',
      'built_in_india': 'இந்தியாவில் உருவாக்கப்பட்டது. உலகிற்காக.',
      'library_sub': 'ஒவ்வொரு மாதிரியும் · ஒவ்வொரு நினைவகமும் · இந்த சாதனத்தில்',
      'on_this_device': 'இந்த சாதனத்தில்',
      'active': 'செயலில்',
      'add': '+ சேர்க்க',
      'storage_used': 'பயன்படுத்தப்பட்ட சேமிப்பு',
      'health_question': 'சுகாதார கேள்வி',
      'family': 'குடும்பம்',
      'work': 'வேலை',
      'just_thinking': 'சும்மா யோசிக்கிறேன்',
    },
    'తెలుగు': {
      'hello': 'నమస్కారం',
      'mind_today': 'ఈరోజు మీ మనస్సులో ఏముంది?',
      'on_device_only': 'ఈ పరికరంలో మాత్రమే',
      'offline': 'ఆఫ్‌లైన్',
      'start_something': 'ప్రారంభించండి',
      'ask_anything': 'ఏదైనా అడగండి',
      'ask_anything_sub': 'ఆరోగ్యం · చట్టపరమైన · వ్యక్తిగత · పని',
      'voice_mode': 'వాయిస్ మోడ్',
      'voice_mode_sub': 'మీ భాషలో మాట్లాడండి',
      'ask_image': 'చిత్రాన్ని అడగండి',
      'ask_image_sub': 'ఫారమ్‌లు, లేబుల్‌లు, స్క్రిప్ట్‌లు',
      'panchang': 'పంచాంగం',
      'panchang_sub': 'నేటి తిథి & ముహూర్తం',
      'ephemeral': 'ఎఫెమెరల్',
      'ephemeral_sub': 'జాడ లేకుండా మాట్లాడండి',
      'recent': 'ఇటీవలి',
      'home': 'హోమ్',
      'chat': 'చాట్',
      'library': 'లైబ్రరీ',
      'you': 'మీరు',
      'settings_pref': 'సెట్టింగ్‌లు · ప్రాధాన్యతలు · గురించి',
      'preferences': 'ప్రాధాన్యతలు',
      'language': 'భాష',
      'security': 'భద్రత',
      'security_sub': 'యాప్ లాక్ · 2FA',
      'privacy_tiers': 'గోప్యతా శ్రేణులు',
      'privacy_tiers_sub': '2 యాక్టివ్ · BrahmAI ఎలా వింటుంది',
      'storage_purge': 'స్టోరేజ్ & పర్జ్',
      'storage_purge_sub': 'పరికరంలో 184 KB',
      'ephemeral_mode': 'ఎఫెమెరల్ మోడ్',
      'about': 'గురించి',
      'reset_prototype': 'ప్రోటోటైప్‌ని రీసెట్ చేయండి',
      'built_in_india': 'భారతదేశంలో నిర్మించబడింది. ప్రపంచం కోసం.',
      'library_sub': 'ప్రతి మోడల్ · ప్రతి మెమరీ · ఈ పరికరంలో',
      'on_this_device': 'ఈ పరికరంలో',
      'active': 'యాక్టివ్',
      'add': '+ జోడించు',
      'storage_used': 'ఉపయోగించిన స్టోరేజ్',
      'health_question': 'ఆరోగ్య ప్రశ్న',
      'family': 'కుటుంబం',
      'work': 'పని',
      'just_thinking': 'ఊరికే ఆలోచిస్తున్నాను',
    },
  };

  /// Looks up and returns the translated string for a given localization key and language.
  /// Falls back to English if the language or key is missing, or returns the raw key as a final safeguard.
  static String translate(String language, String key) {
    if (!_translations.containsKey(language)) {
      return _translations['English']![key] ?? key;
    }
    return _translations[language]![key] ?? _translations['English']![key] ?? key;
  }
}